### ISSUE TITLE
Metrics are too old, data not updating

### ISSUE THREAD

**Issue by Karol1990** [sakrut/hoymiles-dtu-homeassistant-addon#1]
Hello,

I have a problem with addon. At starts it works fine but after few minutes or sometimes hours it gives a message:
_Metrics are XX minutes old. Discarding._
It helps if I restart DTU.

Here is the whole log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:24:30] INFO: /data/options.json exists!
[11:24:30] INFO: MQTT: host=core-mosquitto, port=1883, username=addons, password=***
[11:24:31] INFO: DTU: host=192.168.88.109, port=10081
[11:24:31] INFO: banny310 - Home Assistant Hoymiles DTU Solar Data Gateway Add-on
[11:24:31] INFO: Configuration:
{
  "dtu": {
    "host": "192.168.88.109",
    "port": 10081,
    "watchdog_timeout": 180
  },
  "app": {
    "mode": "active"
  },
  "app_mode_active": {
    "pull_interval": 180
  },
  "app_mode_passive": {},
  "mqtt": {
    "host": "core-mosquitto",
    "port": "1883",
    "username": "addons",
    "password": "***"
  }
}
[11:24:31] INFO: Starting...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  | 2023-10-06 11:24:32 | [main] hoymiles.Entrypoint (Entrypoint.java:15) - Starting...
INFO  | 2023-10-06 11:24:32 | [main] hoymiles.Entrypoint (Entrypoint.java:16) - TimeZone: Europe/Warsaw
INFO  | 2023-10-06 11:24:32 | [main] bootstrap.WeldStartup (WeldStartup.java:148) - WELD-000900: 4.0.3 (Final)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1 (file:/app.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  | 2023-10-06 11:24:32 | [main] bootstrap.WeldStartup (WeldStartup.java:236) - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
INFO  | 2023-10-06 11:24:42 | [main] se.WeldContainer (WeldContainer.java:235) - WELD-ENV-002003: Weld SE container da3fd56e-be74-4ff3-a0de-ebac81843f12 initialized
INFO  | 2023-10-06 11:24:42 | [pool-2-thread-1] infrastructure.App (App.java:79) - Application Hoymiles DTU starting...
INFO  | 2023-10-06 11:24:42 | [pool-2-thread-1] infrastructure.App (App.java:109) - Connecting to DTU: 192.168.88.109:10081 (watchdog_timeout=180)
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:78) - Trying connect to 192.168.88.109:10081
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:87) - Connect success to 192.168.88.109:10081
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] infrastructure.App (App.java:123) - DTU connection success
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] infrastructure.App (App.java:127) - Connecting to MQTT: tcp://core-mosquitto:1883
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] infrastructure.App (App.java:142) - MQTT connection success
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] application.AppController (AppController.java:56) - Successful connected to tcp://core-mosquitto:1883
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] application.AppController (AppController.java:58) - Sending online state...
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] application.AppController (AppController.java:95) - Getting AppInfo from DTU...
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:130) - Sending command: message=com.hoymiles.infrastructure.protos.APPInformationData$APPInfoDataResDTO, responseClazz=com.hoymiles.infrastructure.protos.APPInformationData$APPInfoDataReqDTO
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:120) - --> sending: msgId=41729
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:121) - ymdHms: "2023-10-06 11:24:43", offset: 3600, packageNow: 0, errCode: 0, time: 1696584283, 
INFO  | 2023-10-06 11:24:43 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:115) - --> end
INFO  | 2023-10-06 11:24:45 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:24) - <-- decode: incoming message, length=181
INFO  | 2023-10-06 11:24:45 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:58) - 484da2010001b23d00b5|0a0c34313231413030314442343210b99fffa8061803200a280138014239108f041881ac0228820a380140959fffa806483a52005a0b322e332e302e302d64653a62006815880102900115980121a00114a8010ab201005a1a10b7ca99a3c8ac0420a24e2881e2c980013080023880144081405a1a10b7d299a3c8ac0420a24e2881e2c980013080023880144081405a1a10c2f0e498c8a80420924e2886e2858101308002388014408140
INFO  | 2023-10-06 11:24:45 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:67) - header=HM, msgId=41473, counter=1, dataCrc=45629, msgLen=181
INFO  | 2023-10-06 11:24:45 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:97) - dtuSn: "4121A001DB42", time: 1696583609, deviceNub: 3, pvNub: 10, packageNub: 1, channel: 1, mAPPDtuInfo {,   dtuSw: 527,   dtuHw: 38401,   dtuRfHw: 1282,   accessModel: 1,   communicationTime: 1696583573,   signalStrength: 58,   gprsVsn: "",   wifiVsn: "2.3.0.0-de:",   kaNub: "",   dtuRuleId: 21,   sub1GFqband: 2,   sub1GChtnum: 21,   sub1GChnum: 33,   sub1GRp: 20,   sub1GChtotal: 10,   gprsImei: "", }, mAPPpvInfo {,   pvSn: 19123415704887,   pvSw: 10018,   pvHwPn: 269644033,   pvHw: 256,   pvGpfCode: 2560,   pvGpf: 8193, }, mAPPpvInfo {,   pvSn: 19123415705911,   pvSw: 10018,   pvHwPn: 269644033,   pvHw: 256,   pvGpfCode: 2560,   pvGpf: 8193, }, mAPPpvInfo {,   pvSn: 18985954916418,   pvSw: 10002,   pvHwPn: 270627078,   pvHw: 256,   pvGpfCode: 2560,   pvGpf: 8193, }, 
INFO  | 2023-10-06 11:24:45 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:101) - <-- end
INFO  | 2023-10-06 11:24:45 | [pool-2-thread-1] application.AppController (AppController.java:99) - DTU: hw=38401, sw=527, time=2023-10-06T11:13:29
INFO  | 2023-10-06 11:24:45 | [pool-2-thread-1] application.AppController (AppController.java:101) - Sending autodiscovery...
INFO  | 2023-10-06 11:24:45 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:120) - --> sending: msgId=41745
INFO  | 2023-10-06 11:24:45 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:121) - ymdHms: "2023-10-06 11:24:45", cp: 0, errCode: 0, oft: 3600, time: 1696584285, 
INFO  | 2023-10-06 11:24:45 | [pool-2-thread-1] dtu.DtuClient (DtuClient.java:115) - --> end
INFO  | 2023-10-06 11:24:45 | [pool-2-thread-1] infrastructure.App (App.java:86) - Bootstrap finished. Waiting for incoming messages...
INFO  | 2023-10-06 11:24:47 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:24) - <-- decode: incoming message, length=404
INFO  | 2023-10-06 11:24:47 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:58) - 484da21100011f900194|0a0c34313231413030314442343210bb9fffa806180228014a2d08b7ca99a3c8ac04100118e612208927288e50300838aa0340e70748d60250d40358e5e0016001a001a380bc014a2b08b7d299a3c8ac04100118f61220892728be5038a90340e80748db0250d8035894c6036001a001a880fc014a2d08c2f0e498c8a804100118f31220892728ba45300738ef0240e70748b60250c4035897ef026001a001a280d4015a1f08b7ca99a3c8ac04100118950320c202289c0a30c1ab0238b60140808080185a1f08b7ca99a3c8ac04100218930320c50228a20a30bca10238b50140808080185a1f08b7ca99a3c8ac04100318880320950828852030d0fc0238d40440808080185a1f08b7ca99a3c8ac041004188703208f0828e61f30f2f70238b90440808080185a1f08b7d299a3c8ac04100118950320c40228a50a30feae0238b70140808080185a1f08b7d299a3c8ac04100218950320c202289e0a30b3ad0238b50140808080185a1f08b7d299a3c8ac041003188a03209608289a2030f7fd0238de044080808018
INFO  | 2023-10-06 11:24:47 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:67) - header=HM, msgId=41489, counter=1, dataCrc=8080, msgLen=404
INFO  | 2023-10-06 11:24:47 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:97) - dtuSn: "4121A001DB42", time: 1696583611, packetCount: 2, ver: 1, sgsDatas {,   sn: 19123415704887,   ver: 1,   v: 2406,   freq: 5001,   p: 10254,   q: 8,   i: 426,   pf: 999,   temp: 342,   wnum: 468,   crc: 28773,   link: 1,   miSignal: 3080227, }, sgsDatas {,   sn: 19123415705911,   ver: 1,   v: 2422,   freq: 5001,   p: 10302,   i: 425,   pf: 1000,   temp: 347,   wnum: 472,   crc: 58132,   link: 1,   miSignal: 4128808, }, sgsDatas {,   sn: 18985954916418,   ver: 1,   v: 2419,   freq: 5001,   p: 8890,   q: 7,   i: 367,   pf: 999,   temp: 310,   wnum: 452,   crc: 46999,   link: 1,   miSignal: 3473442, }, pvDatas {,   sn: 19123415704887,   pi: 1,   v: 405,   i: 322,   p: 1308,   et: 38337,   ed: 182,   code: 50331648, }, pvDatas {,   sn: 19123415704887,   pi: 2,   v: 403,   i: 325,   p: 1314,   et: 37052,   ed: 181,   code: 50331648, }, pvDatas {,   sn: 19123415704887,   pi: 3,   v: 392,   i: 1045,   p: 4101,   et: 48720,   ed: 596,   code: 50331648, }, pvDatas {,   sn: 19123415704887,   pi: 4,   v: 391,   i: 1039,   p: 4070,   et: 48114,   ed: 569,   code: 50331648, }, pvDatas {,   sn: 19123415705911,   pi: 1,   v: 405,   i: 324,   p: 1317,   et: 38782,   ed: 183,   code: 50331648, }, pvDatas {,   sn: 19123415705911,   pi: 2,   v: 405,   i: 322,   p: 1310,   et: 38579,   ed: 181,   code: 50331648, }, pvDatas {,   sn: 19123415705911,   pi: 3,   v: 394,   i: 1046,   p: 4122,   et: 48887,   ed: 606,   code: 50331648, }, 
INFO  | 2023-10-06 11:24:47 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:101) - <-- end
INFO  | 2023-10-06 11:24:47 | [nioEventLoopGroup-2-1] dtu.SimpleMessageAggregator (SimpleMessageAggregator.java:31) - First message
INFO  | 2023-10-06 11:24:48 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:24) - <-- decode: incoming message, length=135
INFO  | 2023-10-06 11:24:48 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:58) - 484da2110001cf2f0087|0a0c34313231413030314442343210bb9fffa8061802200128015a1f08b7d299a3c8ac04100418880320930828fa1f30e5fa0238e40440808080185a1f08c2f0e498c8a804100118830320c00928e62430f8ea0338970340808080185a1f08c2f0e498c8a804100218830320be0928d92430ebdb0338e5024080808018
INFO  | 2023-10-06 11:24:48 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:67) - header=HM, msgId=41489, counter=1, dataCrc=53039, msgLen=135
INFO  | 2023-10-06 11:24:48 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:97) - dtuSn: "4121A001DB42", time: 1696583611, packetCount: 2, packetNum: 1, ver: 1, pvDatas {,   sn: 19123415705911,   pi: 4,   v: 392,   i: 1043,   p: 4090,   et: 48485,   ed: 612,   code: 50331648, }, pvDatas {,   sn: 18985954916418,   pi: 1,   v: 387,   i: 1216,   p: 4710,   et: 62840,   ed: 407,   code: 50331648, }, pvDatas {,   sn: 18985954916418,   pi: 2,   v: 387,   i: 1214,   p: 4697,   et: 60907,   ed: 357,   code: 50331648, }, 
INFO  | 2023-10-06 11:24:48 | [nioEventLoopGroup-2-1] dtu.DtuMessageDecoder (DtuMessageDecoder.java:101) - <-- end
INFO  | 2023-10-06 11:24:48 | [nioEventLoopGroup-2-1] dtu.SimpleMessageAggregator (SimpleMessageAggregator.java:40) - Next message, last=true
INFO  | 2023-10-06 11:24:49 | [pool-2-thread-1] application.AppController (AppController.java:73) - Incoming new metrics: time=2023-10-06T11:13:31
WARN  | 2023-10-06 11:24:49 | [pool-2-thread-1] application.AppController (AppController.java:77) - Metrics are 11 minutes old. Discarding.

Hardware Ver.: H09.06.01
Software Ver.: V00.02.15

**Comment by sakrut** [comment]
It just compare time form HA host and Hoymiles. 
https://github.com/banny310/hoymiles-dtu/blob/279929e0ac06f966a7b9c2900b2f4dab868cdb73/src/main/java/com/hoymiles/application/AppController.java#L77C1-L78C1
It look like you have problem on DTU clock. I have the same software but hardware H09.02.02
Try by changing pull_interval and watchdog_timeout to 360

INFO | 2023-10-06 **11:24:49** | [pool-2-thread-1] application.AppController (AppController.java:73) - Incoming new metrics: time=2023-10-06T**11:13:31**

**Comment by sakrut** [comment]
And one more tip, i sow that addon can lock when i use "Instalator" application and i connect to DTU. It look like DTU is ready to emmit data to one applacation, and addon work with dtu as "Instalator" app.

**Comment by Karol1990** [comment]
After connecting to DTU via "Instalator" app the time in incoming metrics is updated and works fine for couple of minutes (sometimes hours). It seems to me that when the time freezes in incoming data, the rest of data is up to date. Can you add "data validity time" parameter?

**Comment by sakrut** [comment]
accepted_data_up_to_min = 5
"mówisz, i masz"
https://github.com/sakrut/hoymiles-dtu/commit/dc9b3d95f9a5383c2d2c2073e20c1f2a6bc2a6d8

**Comment by Karol1990** [comment]
Unfortunately there is some issue:

  "dtu": {
    "host": "192.168.88.109",
    "port": 10081,
    "watchdog_timeout": 60,
    "accepted_data_up_to_min": 6
  },
.
.
.
INFO  | 2023-11-17 11:03:24 | [pool-2-thread-1] application.AppController (AppController.java:102) - Sending autodiscovery...
ERROR | 2023-11-17 11:03:24 | [pool-2-thread-1] hoymiles.Entrypoint (Entrypoint.java:33) - Uncaught exception: merge of system properties,/application.json: 1,reference.conf @ jar:file:/app.jar!/reference.conf: 1: No configuration setting found for key 'accepted_data_up_to_min'
com.typesafe.config.ConfigException$Missing: merge of system properties,/application.json: 1,reference.conf @ jar:file:/app.jar!/reference.conf: 1: No configuration setting found for key 'accepted_data_up_to_min'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157) ~[app.jar:?]
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:175) ~[app.jar:?]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189) ~[app.jar:?]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194) ~[app.jar:?]
	at com.typesafe.config.impl.SimpleConfig.getConfigNumber(SimpleConfig.java:224) ~[app.jar:?]
	at com.typesafe.config.impl.SimpleConfig.getInt(SimpleConfig.java:235) ~[app.jar:?]
	at com.hoymiles.application.AppController.start(AppController.java:104) ~[app.jar:?]
	at com.hoymiles.application.AppController$Proxy$_$$_WeldClientProxy.start(Unknown Source) ~[app.jar:?]
	at com.hoymiles.infrastructure.App.run(App.java:84) ~[app.jar:?]
	at com.hoymiles.Entrypoint.lambda$main$1(Entrypoint.java:31) ~[app.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
INFO  | 2023-11-17 11:03:24 | [pool-2-thread-1] infrastructure.App (App.java:91) - Stopping...
INFO  | 2023-11-17 11:03:24 | [pool-2-thread-1] application.AppController (AppController.java:160) - Stopping...
INFO  | 2023-11-17 11:03:24 | [main] hoymiles.Entrypoint (Entrypoint.java:44) - Shutdown complete

**Comment by Karol1990** [comment]
I think that issue is in the AppControler.java
104        acceptedDataUpToMin = config.getInt("accepted_data_up_to_min");

Should be:
acceptedDataUpToMin = config.getInt("dtu.accepted_data_up_to_min");

**Comment by sakrut** [comment]
yes, fixed, https://github.com/sakrut/hoymiles-dtu/commit/c7a4788262d90bb926875b4aad937268430196a4
in flew minutes i will make images

**Comment by sakrut** [comment]
Done

**Comment by Karol1990** [comment]
Everything works fine after setting **accepted_data_up_to_min: 25**
Thank you very much! :)

There is another issue when temperature is below 0 degrees. Probably variable is set as unsigned in addon.
![image](https://github.com/sakrut/hoymiles-dtu-homeassistant-addon/assets/116189468/494cad8d-5b74-4384-b56a-696274b8d4a4)
